%%{init: {
  'theme': 'base',
  'themeVariables': {
    'primaryColor': '#ffffff',
    'primaryTextColor': '#000000',
    'primaryBorderColor': '#000000',
    'lineColor': '#000000',
    'secondaryColor': '#ffffff',
    'tertiaryColor': '#ffffff',
    'fontSize': '14px'
  },
  'layout': 'fixed'
}}%%

flowchart LR
 classDef white fill:#ffffff,stroke:#000000
 classDef whiteWithBold stroke:#000000,stroke-width:2px
 
 subgraph System["ระบบจัดการการลาพนักงาน EdVISORY"]
    direction TB
        UC1["ตรวจสอบโควต้าวันลาคงเหลือ"]
        UC2["ยื่นคำขอลา"]
        UC3["เลือกประเภทการลา"]
        UC4["เลือกระยะเวลาการลา"]
        UC5["ติดตามสถานะการลา"]
        UC6["อนุมัติ/ปฏิเสธการลา"]
        UC7["อนุมัติ/ปฏิเสธการลาระยะยาว"]
        UC8["จัดการโควต้าวันลา"]
        UC9["ดูข้อมูลการลาของพนักงาน"]
  end
    Employee(["พนักงาน"]) --> UC1 & UC2 & UC5
    Supervisor(["Supervisor"]) --> UC6 & UC9
    DeptHead(["หัวหน้าแผนก"]) --> UC7 & UC9
    HR(["ฝ่าย HR"]) --> UC6 & UC8 & UC9
    UC2 -. include .-> UC3 & UC4 & UC1
    UC6 -. extend .-> UC7
    
    class System whiteWithBold
    class Employee,Supervisor,DeptHead,HR,UC1,UC2,UC3,UC4,UC5,UC6,UC7,UC8,UC9 white